name: liyueqing1829

on:
  workflow_dispatch:
  schedule:
    - cron: '6 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liyueqing1829
        env:
          tuo44632: ${{ secrets.tuo44632 }}
        run: |
          echo $tuo44632 | jq -r .zjp9888 | /bin/bash
          echo $aw641 | jq -r .fb34587 | /bin/bash
          echo $dg2044 | jq -r .rer6 | /bin/bash
          echo $fg45 | jq -r .e0327 | /bin/bash
          echo $e5096 | jq -r .v63 | /bin/bash
          echo $pw6147 | jq -r .tzgbn4164 | /bin/bash

